//common relative
const COMMON = {
    COMMON_UPDATE_SCREEN: "COMMON_UPDATE_SCREEN"
};

//user relative
const USER = {
    API_LOGIN: "API_LOGIN"
};

const SONG = {
    API_GET_RECOMMEND: "API_GET_RECOMMEND",
    API_PUSH: "API_PUSH",
    API_CHOOSE_LIST: "API_CHOOSE_LIST",
    API_SET_SONG_TOP: "API_SET_SONG_TOP",
    API_GET_SINGER_CATEGORY_ALBUM: "API_GET_SINGER_CATEGORY_ALBUM",
    API_GET_ACTORS_ALBUM: "API_GET_ACTORS_ALBUM",
    API_GET_CAT_ALBUM: "API_GET_CAT_ALBUM",
    API_GET_CAT_SONG_LIST: "API_GET_CAT_SONG_LIST",
    API_GET_RANK_ALBUM: "API_GET_RANK_ALBUM"
};
//audio relative
const AUDIO = {
    API_GET_SHARE_AUDIO: "API_GET_SHARE_AUDIO"
};

const SEARCH = {
    API_GET_HOT_WORD: "API_GET_HOT_WORD",
    API_SEARCH: "API_SEARCH"
};

export default {
    COMMON,
    USER,
    AUDIO,
    SONG,
    SEARCH
};


